///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppImages {
  AppImages._();

  static const String fontsKarlaBold = 'assets/fonts/Karla-Bold.ttf';
  static const String fontsKarlaMedium = 'assets/fonts/Karla-Medium.ttf';
  static const String fontsKarlaRegular = 'assets/fonts/Karla-Regular.ttf';
  static const String fontsKarlaSemiBold = 'assets/fonts/Karla-SemiBold.ttf';
  static const String imagesAdd = 'assets/images/add.svg';
  static const String imagesAddLocationAlt =
      'assets/images/add_location_alt.svg';
  static const String imagesApple = 'assets/images/apple.svg';
  static const String imagesArrowForward = 'assets/images/arrow_forward.svg';
  static const String imagesBadges = 'assets/images/Badges.svg';
  static const String imagesBody = 'assets/images/Body.png';
  static const String imagesBusiness = 'assets/images/business.svg';
  static const String imagesCall = 'assets/images/Call.svg';
  static const String imagesCategory = 'assets/images/category.svg';
  static const String imagesCheck = 'assets/images/Check.svg';
  static const String imagesCheckCircle = 'assets/images/check_circle.svg';
  static const String imagesClose = 'assets/images/close.svg';
  static const String imagesDashboard = 'assets/images/dashboard.svg';
  static const String imagesEdit = 'assets/images/edit.svg';
  static const String imagesEmail = 'assets/images/email.svg';
  static const String imagesGoogle = 'assets/images/google.svg';
  static const String imagesHighlight1 = 'assets/images/Highlight1.svg';
  static const String imagesHighlight2 = 'assets/images/Highlight2.svg';
  static const String imagesHighlight3 = 'assets/images/Highlight3.svg';
  static const String imagesHighlight4 = 'assets/images/Highlight4.svg';
  static const String imagesHighlight5 = 'assets/images/Highlight5.svg';
  static const String imagesIconStar = 'assets/images/IconStar.svg';
  static const String imagesImage = 'assets/images/Image.png';
  static const String imagesImageteeth = 'assets/images/Imageteeth.png';
  static const String imagesInsertDriveFile =
      'assets/images/insert_drive_file.svg';
  static const String imagesLibraryAddCheck =
      'assets/images/library_add_check.svg';
  static const String imagesLocalHotel = 'assets/images/local_hotel.svg';
  static const String imagesLocalOffer = 'assets/images/local_offer.svg';
  static const String imagesLock = 'assets/images/lock.svg';
  static const String imagesLogin = 'assets/images/login.svg';
  static const String imagesLoginPageHero = 'assets/images/LoginPageHero.png';
  static const String imagesLogo = 'assets/images/Logo.svg';
  static const String imagesLogo2 = 'assets/images/Logo2.svg';
  static const String imagesMilitaryTech = 'assets/images/military_tech.svg';
  static const String imagesMonetizationOn =
      'assets/images/monetization_on.svg';
  static const String imagesMoreVert = 'assets/images/more_vert.svg';
  static const String imagesPayment = 'assets/images/payment.svg';
  static const String imagesPeople = 'assets/images/people.svg';
  static const String imagesPermContactCalendar =
      'assets/images/perm_contact_calendar.svg';
  static const String imagesPerson = 'assets/images/person.png';
  static const String imagesPlus = 'assets/images/plus.svg';
  static const String imagesSave = 'assets/images/save.svg';
  static const String imagesSearch = 'assets/images/Search.svg';
  static const String imagesSecurity = 'assets/images/security.svg';
  static const String imagesSend2 = 'assets/images/send2.svg';
  static const String imagesSettings = 'assets/images/settings.svg';
  static const String imagesShoppingCart = 'assets/images/shopping_cart.svg';
  static const String imagesSort = 'assets/images/sort.svg';
  static const String imagesStar = 'assets/images/Star.svg';
  static const String imagesStorefront = 'assets/images/storefront.svg';
  static const String imagesSupportAgent = 'assets/images/support_agent.svg';
  static const String imagesTrue = 'assets/images/true.svg';
  static const String imagesUpload = 'assets/images/upload.svg';
  static const String imagesVector = 'assets/images/Vector.svg';
  static const String imagesView = 'assets/images/view.svg';
  static const notigications = 'assets/images/notifications.svg';
  static const calendar = 'assets/images/calendar.svg';
  static const eye = 'assets/images/eye.svg';
  static const history = 'assets/images/history.svg';
  static const campaign = 'assets/images/campaign.svg';
  static const save2 = 'assets/images/save2.svg';
}
